# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cartproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Its a thing'),
            preserve_default=False,
        ),
    ]
