# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='description',
            field=models.TextField(default='description of a cart item'),
            preserve_default=False,
        ),
    ]
