# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='limited_integer_field',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
